### ISSUE TITLE
Need to login twice for session to update

### ISSUE THREAD

**Issue by peavers** [auth0-community/ember-simple-auth-auth0#114]
Some strange issue happening at the moment where the first login while is successful as far as auth0 cares (shows up in logs as success) it doesn't seem to load the session up correctly. Everything to do with the session still thinks you're logged out. If you login again, things work as expected, the session is correctly created and life goes on. 

Version:
```
"ember-simple-auth-auth0": "^4.0.0-beta.2",
```

Login 
```
export default Controller.extend({
  session: service(),

  actions: {

    login() {
      const lockOptions = {
        autoclose: true,
        autofocus: true,
        closable: true,
        auth: {
          oidcConformant: true,
          auth: {
            params: {
              scope: 'openid profile email user_metadata',
            },
          }
        }
      };

      get(this, 'session').authenticate('authenticator:auth0-lock', lockOptions);
    },
});
```
environment.js
```
  ENV['ember-simple-auth'] = {
    authenticationRoute: '/',
    routeAfterAuthentication: 'news',
    routeIfAlreadyAuthenticated: 'news',
    auth0: {
      clientID: 'xxxx',
      domain: 'xxxx'
    }
  };
```
session value after first login
```
ember_simple_auth-session: {"authenticated":{}}
```
After opening the login dialog but not pressing anything (weird i know) the session gets populated.

**Comment by XaserAcheron** [comment]
Hmm, I'm not able to reproduce this. Which browser are you using? In a perfect world, it wouldn't matter, but we all know how these things go. :P

About the only thing I can suggest offhand is to double-check that if you have any overridden beforeModel/afterModel/etc. hooks in your application route that they're calling `this._super(...arguments)` at some point. This addon relies pretty heavily on its ApplicationRouteMixin to do its stuff, and things can break in subtle, strange ways if it doesn't (I know from experience D:).

Shot in the dark, but maybe it's something.

**Comment by peavers** [comment]
Fixed with information from #116

**Comment by Kilowhisky** [comment]
I hate to bring this back from the dead but i'm having this issue with my new app.

i'm on the dev branch FYI. 

It works like the following:

1) session.authenticate is called
2) user is redirected where the login with google
3) authentication succeeds and page is reloaded with "#token.../..sdlfjsldf in URL. promise is NOT resolved and the session state is NOT updated.
4) user clicks login again.
5) Session is immediately updated and promise resolves
6) User is prompted with login window again

Here is the commit where this stuff was added:
The repo is easily demoable at the moment by going to '/login' route manually. 

https://github.com/Kilowhisky/ember-website/commit/fdba587b65f613d672c3bf2294c83531171acc0d

Here is relevant sections: 


`
// login.route.js
export default Route.extend({
  session: service(),
  actions: {
    login() {
      const lockOptions = {
        closable: false,
        allowSignUp: false,
        auth: {
          params: {
            scope: 'openid user_metadata'
          }
        },
      };

      this.session.authenticate('authenticator:auth0-lock', lockOptions)
        .then(() => this.transitionTo('admin'));
    }
  }
});
`

Any thoughts?

**Comment by XaserAcheron** [comment]
@Kilowhisky Try adding ApplicationRouteMixin to application/route.js, like so:

```js
//app/ui/application/route.js

import Route from '@ember/routing/route';
import { inject as service } from '@ember/service';
import ApplicationRouteMixin from 'ember-simple-auth-auth0/mixins/application-route-mixin';

export default Route.extend(ApplicationRouteMixin, {
  session: service(),
  notifications: service('notification-messages'),
  actions: {
    logout() {
      this.session.invalidate();
      this.notifications.success('Logged Out', { autoClear: true });
    }
  }
});
```

That mixin is unfortunately required to make everything work properly under the hood. It's probably worth throwing a warning if the lock is called and the mixin isn't present, since it isn't super-obvious to do this.

Hope this helps!

**Comment by Kilowhisky** [comment]
@XaserAcheron Yep that did it.

I glazed over the fact that the application route mixin was specific to this package and not the same one called out by ember-simple-auth as i've used ember-simple-auth by itself many times.

```
import ApplicationRouteMixin from 'ember-simple-auth-auth0/mixins/application-route-mixin';
```

Thanks!

**Comment by XaserAcheron** [comment]
Glad it's working now! :D

The fact that there's an extra-special mixin for this addon is a common point of confusion, I've found. I wouldn't mind seeing that change someday, though there's bigger fish to fry at the moment.
